### ISSUE TITLE
Git workflow slide: Are feature branches long-lived?

### ISSUE THREAD

**Issue by christophjahn** [SoftwareAG/webmethods_io_int_cicd#1]
When looking at slide 9 of the presentation [webMethodsIO_Integration_CICD.pptx](https://github.com/SoftwareAG/webmethods_io_int_cicd/blob/main/presentation/webMethodsIO_Integration_CICD.pptx) it is unclear to me how long a separate feature branch is supposed to exist.

If we are talking about more than one or two day, that will likely cause problems. It also means that by definition we are not talking about CI anymore.

What is your view on that? Wouldn't it make sense to at least mention trunk-based development as the approach that is endorsed (put mildly) by the inventors of CD?

Thanks,
Christoph

**Comment by chini007** [comment]
Hey @christophjahn 

Strangely Github didnt notify me on your issue (or may be I missed the mail, which is more probable and possible).

Very valid point. So the Git Workflow I have chosen as a sample is from one of the customer, where they use feature branches which is kept until Prod merge. They have 5 days releases. They follow more of a Gitflow than Trunk based. Again am not promoting any model here, rather took one example on which the solution was primary developed.

**Comment by christophjahn** [comment]
No problem about the delay, the same has happened to me multiple times ;-).

As to the slides, may I suggest to add what you wrote here. Otherwise folks might actually get the impression that SAG promotes this approach.

**Comment by chini007** [comment]
Did get the notification this time :)

Yes makes sense, will do that. Thanks.

**Comment by chini007** [comment]
Updated the deck, will close the issue

**Comment by christophjahn** [comment]
Thanks!
